# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: deploy frontend
      run: |
          cd ~/actions-runner/_work/cc-project/cc-project/frontend 
          npm i
          npm install pm2 -g
          pm2 ps
          pm2 restart frontend
    - name: deploy backend
      run: |
          cd ~/actions-runner/_work/cc-project/cc-project/backend 
          npm i
          npm install pm2 -g
          pm2 restart bacend
      
